"""Stdlib-only constants for the external hook worker protocol."""

ID = "id"
KIND = "kind"
READY = "ready"
MODULE = "module"
CONTENT = "content"
INPUTS = "inputs"
TARGET = "target"
FILE = "file"
ARGS = "args"
OK = "ok"
RESULT = "result"
ERROR = "error"

TRANSFORM = "transform"
VALIDATE = "validate"
